# -*- coding: utf-8 -*-
"""examen4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzWr3jbR7vAYH4FdNKpzyYh_oX4jflJR
"""

import numpy as np
import streamlit as st
import pandas as pd
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier


st.write(''' # Predicción de temperatura ''')
st.image("gastos.jpg", caption="predicción de temperatura de mexico")

st.header('Datos de evaluación')

def user_input_features():
  # Entrada
  Pclass = st.number_input('Clase{Acapulco:0, Aguascalientes:1, Acuña:2}:', min_value=1, max_value=3, value = 1, step = 1)
  Sex = st.number_input('mes:', min_value=0, max_value=1, value = 0, step = 1)
  Age = st.number_input('año:', min_value=0, max_value=100, value = 0, step = 1)

  user_input_data = {'clase': clase,
                     'mes': mes,
                     'año': año,}

  features = pd.DataFrame(user_input_data, index=[0])

  return features

df = user_input_features()

examen =  pd.read_csv('EXAMEN2.csv', encoding='latin-1')
X = examen.drop(columns='AverageTemperature')
Y = examen['AverageTemperature']

classifier = DecisionTreeClassifier(max_depth=3, criterion='gini', min_samples_leaf=25, max_features=4, random_state=1613497)
classifier.fit(X, Y)

prediction = classifier.predict(df)

st.subheader('Predicción de temperatura')