# -*- coding: utf-8 -*-
"""examen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwRGMazSE3TPRO8NUyCXTw-8AQi7bUGK
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df = pd.read_csv ("AmericaTemperaturesByCity.csv",encoding="latin-1")

df.drop(columns=["AverageTemperatureUncertainty", "Latitude", "Longitude"], inplace=True)
df

paises = df['Country'].unique()
print(paises)

df = df[df['Country'] == 'Mexico']
df

ciudades = df['City'].unique()
print(ciudades)

df.isnull().sum(axis=0)

df.dropna (subset=["AverageTemperature"], inplace= True)
df.isnull().sum(axis=0)

df["dt"] = pd.to_datetime(df["dt"])
df["year"]= df ["dt"].dt.year
df["month"]= df ["dt"].dt.month
df["day"]= df ["dt"].dt.day

df.drop(columns=["dt","Country"], inplace=True)
df

df.replace({"City":{"Acapulco":0, 'Aguascalientes':1, "Acuña":2}}, inplace=True)
df

sns.heatmap(df.isnull())

AmericaTemperaturesByCity.to_csv("EXAMEN3.csv", index=False)
df.to_csv("EXAMEN3.csv", index=False)

X = pd.DataFrame(df.drop(columns=["AverageTemperature"]))
y = df['AverageTemperature']
X

X = df[["City", "year", "month", "day"]]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)
y_train

from sklearn.linear_model import LinearRegression
LR = LinearRegression()

LR.fit(X_train,y_train)

LR.score(X_train, y_train)

pred = LR.predict(X_test)
pred

b1 = LR.coef_
print("Coeficiente b1: \n", b1)

b0 = LR.intercept_
print("Intersección: \n", b0)

comp = X_test.copy()
comp = comp.join(y_test)
comp['Predicción'] = pred
comp

X.columns